name = "cafe-api"
main="src/index.ts"

compatibility_date = "2022-11-22"
node_compat = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "cafe-db-d1"
database_id = "5f40ee56-69dd-4dbf-b7b5-b240710da610"